# Undertow settings
server:
  port: ${UNDERTOW_SERVER_PORT:8080}
  undertow:
    io-threads: 1
    worker-threads: 8
    buffer-size: 1024

# Management settings
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

# Logging settings
logging:
  level:
    root: INFO
    org:
      springframework:
        security: INFO
        web: ERROR
      hibernate: INFO
    com:
      example: DEBUG
  file:
    path: ${LOGGING_FILE_PATH:./}
    name: output.log
    max-size: ${LOGGING_FILE_MAX_SIZE:100MB}
    max-history: ${LOGGING_FILE_MAX_HISTORY:50}

# Spring settings
spring:
  profiles:
    active: dev
  application:
    name: springboot
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
